name = "r2-worker"
main = "src/index.ts"
compatibility_date = "2024-02-13"

[[r2_buckets]]
binding = "PARASCAPE_BUCKET"
bucket_name = "parascape-bucket"

[vars]
ALLOWED_ORIGIN = "https://parascape.org"
SUPABASE_URL = "https://hpuqzerpfylevdfwembv.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwdXF6ZXJwZnlsZXZkZndlbWJ2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczOTUxMjA4MiwiZXhwIjoyMDU1MDg4MDgyfQ.3U72os4aO9g7rc3Dg4ewMh198J-XZ8j4-iS-UKBkyDo"

# Custom domain configuration
routes = [
  { pattern = "r2.parascape.org", custom_domain = true }
]

# Worker configuration
[build]
command = "npm run build"
watch_dir = "src"

[dev]
port = 8787

# Configure timeouts and limits
[limits]
cpu_ms = 50
memory_mb = 128
uploader_size_mb = 100

# Configure CORS headers for multiple origins
[[headers]]
for = "/*"
[headers.response]
Access-Control-Allow-Origin = "https://parascape.org"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Max-Age = "86400"

[[headers]]
for = "/*"
[headers.response]
Access-Control-Allow-Origin = "https://www.parascape.org"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Max-Age = "86400" 