name = "r2-worker"
main = "src/index.ts"
compatibility_date = "2024-02-13"

[[r2_buckets]]
binding = "PARASCAPE_BUCKET"
bucket_name = "parascape-bucket"

[vars]
ALLOWED_ORIGIN = "https://parascape.org"

# Configure CORS headers
[[headers]]
for = "/*"
[headers.response]
Access-Control-Allow-Origin = "https://parascape.org"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Max-Age = "86400" 