name = "send-email"
main = "src/index.js"
compatibility_date = "2024-02-12"

[vars]
# The variables will be set in the Cloudflare dashboard

[[routes]]
pattern = "parascape.org/api/send-email"
zone_name = "parascape.org" 